---
# tasks file for lofar

- name: install LSMTool
  pip: name='https://github.com/darafferty/LSMTool/archive/master.zip' extra_args='--allow-external --upgrade'
  sudo: True
  
- name: install LoSoTo
  pip: name='https://github.com/revoltek/losoto/archive/master.zip' extra_args='--allow-external --upgrade'
  sudo: True

- name: Download source of WSClean
  get_url: >
    url=http://sourceforge.net/projects/wsclean/files/wsclean-1.11/wsclean-1.11.tar.bz2/download 
    dest=/tmp/wsclean-1.11.tar.bz2
# Alternative http://www.roe.ac.uk/~jsm/lofar_dist/src/wsclean-1.10.tar.bz2
    
- name: Compile and install WSClean
  script: wsclean.sh creates=/usr/bin/wsclean
  sudo: True
  
- name: download LOFAR package
  get_url: url=http://www.roe.ac.uk/~jsm/lofar_dist/trusty/lofar_2.15-1trusty_amd64.deb dest=/tmp/lofar_2.15-1trusty_amd64.deb

- name: Install LOFAR package
  apt: deb=/tmp/lofar_2.15-1trusty_amd64.deb
  sudo: True

- name: Remove temporary package
  file: path=/tmp/lofar_2.15-1trusty_amd64.deb state=absent

- name: copy LOFAR profile file
  copy: src=lofar_profile dest=/etc/profile.d/Z98-lofar.sh owner=root group=root mode=0755
  sudo: True
  
- name: install factor
  pip: name='https://github.com/revoltek/factor/archive/master.zip' extra_args='--allow-external --upgrade'
  sudo: True
  
# TODO: Patch pipeline here
#- name: patch pipeline file to use factor
  #copy: >
    #src=utilities.py 
    #dest=/opt/LofIm-2_12/lib/python2.7/dist-packages/lofarpipe/support/utilities.py
    #owner=root 
    #group=root 
    #mode=0644
  #sudo: True