---
# tasks file for lofar
- name: update box
  apt: upgrade=dist update_cache=yes
  sudo: True

- name: install dependencies
  apt: pkg={{ item }}
  sudo: True
  with_items:
    - fail2ban
    - gfortran 
    - cmake 
    - scons 
    - fftw3-dev 
    - flex 
    - libreadline-dev 
    - libcfitsio3 
    - libcfitsio3-dev 
    - libxml2-dev 
    - libpng-dev 
    - libblas-dev 
    - liblapack-dev 
    - bison 
    - libboost-all-dev
    - f2c 
    - zlib1g-dev 
    - subversion 
    - libfreetype6-dev 
    - make 
    - libncurses5-dev 
    - git 
    - libatlas-base-dev
    - wcslib-dev 
    - hdf5-tools 
    - libhdf5-dev 
    - libhdf5-serial-dev 
    - build-essential 
    - libzmq-dev 
    - liblzo2-dev 
    - valgrind 
    - libssh2-1-dev 
    - libblitz0-dev 
    - autogen 
    - libpqxx3-dev 
    - libpq-dev 
    - libunittest++-dev
    - liblog4cplus-dev
    - libgsl0-dev
    - xvfb
    - libffi-dev
    - libssl-dev
      
- name: install Python packages
  apt: pkg={{ item }}
  sudo: True
  with_items:  
    - ipython 
    - python-matplotlib 
    - python-matplotlib-data 
    - python-pip 
    - python-pyfits 
    - python-numpy 
    - python-scipy 
    - python-virtualenv 
    - python-sphinx
    - python-pygments 
    - python-jinja2 
    - python-nose 
    - python-tornado 
    - cython 
    - python-zmq 
    - python-pywcs 
    - python-astropy 
    - python-numexpr 
    - python-tables 
    - python-pandas
    - ipython-notebook 
    - ipython-qtconsole
    - python-h5py

- name: Update pip to the last version
  script: update_pip.sh
  sudo: True
  
- name: install additional Python packages with pip
  pip: name={{ item }} extra_args="--upgrade"
  sudo: True
  with_items:  
    - pyopenssl 
    - ndg-httpsclient
    - pyasn1
    - astropy
    - aplpy
    - unittest-xml-reporting
    - psutil
    - progressbar
    - wcsaxes
    - fabric
    - jupyter
    - ipython
    - ipyparallel
    
- name: install LOFAR dependencies repository
  apt_repository: repo='ppa:jsm-8/lofar-deps'
  sudo: True

- name: install LOFAR dependencies
  apt: pkg={{ item }} update_cache=yes
  sudo: True
  with_items:
    - casacore
    - libcasacore-dev
    - python-pyrap
    - casarest 
    - libcasarest-dev
    - casacore-data

    
- name: install LSMTool
  pip: name='https://github.com/darafferty/LSMTool/archive/master.zip' extra_args='--allow-external --upgrade'
  sudo: True
  
  
- name: install LoSoTo
  pip: name='https://github.com/revoltek/losoto/archive/master.zip' extra_args='--allow-external --upgrade'
  sudo: True
  
  
- name: Download source of WSClean
  get_url: >
    url=http://sourceforge.net/projects/wsclean/files/wsclean-1.8/wsclean-1.8.tar.bz2/download 
    dest=/tmp/wsclean-1.8.tar.bz2
# Alternative http://www.roe.ac.uk/~jsm/lofar_dist/src/wsclean-1.8.tar.bz2
    
- name: Compile and install WSClean
  script: wsclean.sh creates=/usr/bin/wsclean
  sudo: True

  
- name: Download the source code of Montage
  get_url: >
    url=http://montage.ipac.caltech.edu/download/Montage_v3.3.tar.gz
    dest=/tmp/Montage_v3.3.tar.gz

- name: Unarchive Montage in /opt
  unarchive: >
    src=/tmp/Montage_v3.3.tar.gz 
    dest=/opt
    copy=no
  sudo: True

- name: Compile Montage
  command: make
  args:
    chdir: /opt/Montage_v3.3/
    creates: /opt/Montage_v3.3/bin/mProject
  sudo: True
#    creates: /path/to/database

- name: Add /opt/Montage_v3.3/bin to system path
  lineinfile: >
    dest=/etc/environment
    state=present
    backrefs=yes
    regexp='PATH=(["]*)((?!.*?/opt/Montage_v3.3/bin).*?)(["]*)$'
    line="PATH=\1\2:/opt/Montage_v3.3/bin\3"
  sudo: True

- name: install montage-wrapper
  pip: name=montage-wrapper extra_args="--upgrade"
  sudo: True
  
- name: Remove temporary package
  command: /bin/rm /tmp/Montage_v3.3.tar.gz removes=/tmp/Montage_v3.3.tar.gz
  
  
- name: download LOFAR package
  get_url: url=http://www.roe.ac.uk/~jsm/lofar_dist/trusty/lofar_2.10-1trusty_amd64.deb dest=/tmp/lofar_2.10-1trusty_amd64.deb

- name: Install LOFAR package
  apt: deb=/tmp/lofar_2.10-1trusty_amd64.deb
  sudo: True

- name: Remove temporary package
  command: /bin/rm /tmp/lofar_2.10-1trusty_amd64.deb removes=/tmp/lofar_2.10-1trusty_amd64.deb

- name: copy LOFAR profile file
  copy: src=lofar_profile dest=/etc/profile.d/Z98-lofar.sh owner=root group=root mode=0755
  sudo: True
