---
# For an m4.4xlarge instance
volume_size: 2000
volume_type: "st1"
key_name: "jsmkey"
instance_type_v: "m4.4xlarge"
spot_price_v: 1
device_name: "/dev/xvdb"
security_group: "ska"
ami: "ami-bdab83c6"
