---
# For an r3.2xlarge instance
volume_size: 2000
volume_type: "st1"
key_name: "jsmkey"
instance_type_v: "r3.2xlarge"
spot_price_v: 1
device_name: "/dev/xvdf"
ami: "ami-f7d4d0e0"
n_cores: 8
memory: 61

