---
cals: [
        ["009", "cal1", "L229062"],
        ["010", "cal1", "L229310"],
        #["012", "cal1", "L229671"],
        ["013", "cal1", "L230459"],
        ["014", "cal1", "L230777"],
        ["015", "cal1", "L231209"],
        ["016", "cal1", "L231503"],
        ["017", "cal1", "L231645"],
        ["018", "cal1", "L232979"],
        ["019", "cal1", "L233802"],
      ]
count: "{{ cals | length }}"
bucket_name: "lofar-elais-n1-calibration"
pipeline_name: "pre_facet_cal_rawdata"