---
cals: [
        #{ "dataset": "012", "cal_name": "cal1", "data_id": "L229671"}
        ["012", "cal2", "L229671"],
        #["013", "cal1", ""],
        #["013", "cal2", ""],
      ]
count: "{{ cals | length }}"
bucket_name: "lofar-elais-n1-calibration"
pipeline_name: "pre_facet_cal_rawdata"