---
- name: Setup spot calibration instance
  hosts: localhost
  vars:
  - instance_name: "pretarget0"
  - instance_type: "m4_4xlarge"
  - calibration_type: "pretarget"
  vars_files:
  - "{{ instance_type|default('m4_4xlarge') }}_{{ calibration_type|default('pretarget') }}.yml"
  tasks:
  - name: Launch spot instance
    ec2:
      image: ami-bf3507d5
      region: us-east-1
      instance_type: "{{ instance_type_v }}"
      spot_price: "{{ spot_price_v }}"
      key_name: "{{ key_name }}"
      group: [ska]
      instance_tags: { Name: "{{ instance_name }}", type: "{{ calibration_type }}", env: production, iname: "{{ instance_name }}" }
      wait: yes
      monitoring: yes
      exact_count: 1
      count_tag: { iname: "{{ instance_name }}" }
    register: ec2
    tags:
    - launch
  
  - name: add the instance to the inventory
    add_host: name={{ item.public_ip }} groups=cal,production
    with_items: '{{ec2.tagged_instances}}'
    when: item.public_ip is defined
    tags:
    - launch
  
  - name: update dns records
    route53:
      command: create
      zone: "lofarcloud.uk"
      record: "{{ instance_name }}.lofarcloud.uk"
      type: A
      ttl: 300
      value: "{{ item.public_ip }}"
      overwrite: True
    with_items: '{{ec2.tagged_instances}}'
    tags:
    - launch
    - dns
 
  - name: Attach data disk
    ec2_vol:
      region: us-east-1
      instance: "{{ item.id }}"
      volume_size: "{{ volume_size }}"
      volume_type: "{{ volume_type }}"
      name: "{{ instance_name }}"
      device_name: /dev/xvdb
    with_items: '{{ec2.tagged_instances}}'
    register: ec2_vol
    tags:
    - mount_disk

    
    
  

