---
- name: Run the calibration process
  hosts: pretarget
  vars:
  - band: "0"
  - pipeline_name: "pre_facet_pretarget"
  - bucket_name: "lofar-elais-n1-calibration"
  - dataset_name: "011"
  - calibrator_name: "cal1"
  tasks:
  
  - name: launch profile process
    command: "screen -dmS profile bash -c 'cd /mnt/scratch/data/log; python /home/ubuntu/astrocompute/pipeline/scripts/profile_node.py'; sleep 1"
    async: 45
    poll: 0
    tags:
    - profile
  
  
  - name: Create pipeline directory
    file: >
      path=/mnt/scratch/data/cal/{{ pipeline_name }}
      state=directory
      owner=ubuntu 
      group=ubuntu 
      mode=0755
    tags:
    - download_cal
    
  - name: Generate download script
    template: >
      src=templates/download_data_cal.sh.j2 
      dest=/home/ubuntu/download_data_cal.sh
      owner=ubuntu 
      group=ubuntu 
      mode=0755
    tags:
    - download_cal
  
  - name: Execute download of calibrator data script
    command: ./download_data_cal.sh 
    args:
      chdir: /home/ubuntu
    #async: 500
    #poll: 10
    tags:
    - download_cal
  
  # Adapt to gather band from facts !!!!
  - name: launch download of data
    command: "screen -dmS download bash -c '/home/ubuntu/astrocompute/pipeline/scripts/parallel_download.sh /home/ubuntu/astrocompute/pipeline/data/target-BAND{{ band }}.txt'; sleep 1"
    async: 45
    poll: 0
    tags:
    - download
    
  
  
  
  
  