---
- name: Install LOFAR software and then the postgres 8.4.10 db
  hosts: default
  roles:
    - lofar
    - grid
  post_tasks: #####
    - name: Install the dependencies to build it
      apt: pkg={{ item }}
      sudo: True
      with_items:
        - build-essentials
    
    - name: Download
      get_url: >
        url=https://ftp.postgresql.org/pub/source/v8.4.10/postgresql-8.4.10.tar.gz
        dest=/tmp/postgresql-8.4.10.tar
    
    - name: Extract
      unarchive: src=/tmp/postgresql-8.4.10.tar dest=/tmp/postgresql-8.4.10
    
    - name: extract, compile and install
      command: "{{ item }}"
      args:
        chdir: "/tmp/postgresql-8.4.10"
        creates: "/opt/postgres"
      sudo: True
      with_items:
        - ./configure --prefix=/opt/postgres
        - make
        - make install
