---
- name: Compile LOFAR software
  hosts: default
  gather_facts: False
  pre_tasks:
  - name: Install python for Ansible
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    changed_when: False
    become: True
  - setup:
  roles:
    - lofar_base
  post_tasks:
  - name: Prepare compilation of LOFAR
    command: /usr/bin/python /vagrant/package_LOFAR/package_LOFAR.py
  - name: Compile LOFAR
    command: /vagrant/package_LOFAR/package.sh
    become: True
