---
# tasks file for wsclean
- name: Download source of WSClean
  get_url: >
    url=http://sourceforge.net/projects/wsclean/files/wsclean-1.10/wsclean-1.10.tar.bz2/download
    dest=/tmp/wsclean-1.8.tar.bz2
- name: Compile and install WSClean
  script: wsclean.sh
  become: True