---
# tasks file for wsclean
- name: Download source of WSClean
  get_url: >
    url=http://sourceforge.net/projects/wsclean/files/wsclean-2.2/wsclean-2.2.1.tar.bz2/download
    dest=/tmp/wsclean-2.2.1.tar.bz2
- name: Compile and install WSClean
  script: wsclean.sh
  become: True