---
# tasks file for casa
- name: download casa tar file
  get_url: url=https://svn.cv.nrao.edu/casa/linux_distro/old/casapy-42.2.30986-1-64b.tar.gz dest=/tmp/casapy-42.2.30986-1-64b.tar.gz sha256sum=e178b8005efeb9eee60f809f1eef6d55a5cd29b9b62b1a5a3103277635188f0c
  
- name: unpack the casa tar file
  unarchive: src=/tmp/casapy-42.2.30986-1-64b.tar.gz dest=/opt copy=no
  sudo: True

- name: create symbolic link in /opt
  file: src=/opt/casapy-42.2.30986-1-64b dest=/opt/casapy state=link
  sudo: True

- name: Remove temporary package
  command: /bin/rm /tmp/casapy-42.2.30986-1-64b.tar.gz removes=/tmp/casapy-42.2.30986-1-64b.tar.gz

- name: add /opt/casapy/bin to system path
  lineinfile: >
    dest=/etc/environment
    state=present
    backrefs=yes
    regexp='PATH=(["]*)((?!.*?/opt/casapy/bin).*?)(["]*)$'
    line="PATH=\1\2:/opt/casapy/bin\3"
  sudo: True

- name: copy casarc file
  copy: src=casarc dest=/etc/casarc owner=root group=root mode=0644
  sudo: True
  
- name: add CASARCFILES to system environment variables
  lineinfile: >
    dest=/etc/environment
    state=present
    regexp='^CASARCFILES="/etc/casarc"'
    line="CASARCFILES=\"/etc/casarc\""
  sudo: True