---
- name: Finish the calibration of the calibrator
  hosts: cal
  vars: 
  - bucket_name: "lofar-elais-n1-calibration"
  - main_pipeline_name: "pre_facet_cal_rawdata"
  - resume_pipeline_name: "pre_facet_cal_rawdata_2ndround"
  - dataset_name: "011"
  - calibrator_name: "cal1"
  tasks:
  
  - name: Generate upload script
    template: >
      src=templates/upload_data_cal.sh.j2 
      dest=/home/ubuntu/upload_data_cal.sh
      owner=ubuntu 
      group=ubuntu 
      mode=0755
    tags:
    - upload

  - name: Execute upload script
    command: "screen -dmS upload bash -c 'cd /home/ubuntu; ./upload_data_cal.sh'; sleep 1"
    async: 45
    poll: 0
    tags:
    - upload
    
