---
# tasks file for lofar_base
- name: update box
  apt: upgrade=dist update_cache=yes
  sudo: True

- name: install dependencies
  apt: pkg={{ item }}
  sudo: True
  with_items:
    - fail2ban
    - gfortran 
    - cmake 
    - scons 
    - fftw3-dev 
    - flex 
    - libreadline-dev 
    - libcfitsio3 
    - libcfitsio3-dev 
    - libxml2-dev 
    - libpng-dev 
    - libblas-dev 
    - liblapack-dev 
    - bison 
    - libboost-all-dev
    - f2c 
    - zlib1g-dev 
    - subversion 
    - libfreetype6-dev 
    - make 
    - libncurses5-dev 
    - git 
    - libatlas-base-dev
    - wcslib-dev 
    - hdf5-tools 
    - libhdf5-dev 
    - libhdf5-serial-dev 
    - build-essential 
    - libzmq-dev 
    - liblzo2-dev 
    - valgrind 
    - libssh2-1-dev 
    - libblitz0-dev 
    - autogen 
    - libpqxx3-dev 
    - libpq-dev 
    - libunittest++-dev
    - liblog4cplus-dev
    - libgsl0-dev
    - xvfb
    - libffi-dev
    - libssl-dev
    - software-properties-common
    - libgeos-dev
      
- name: install Python packages
  apt: pkg={{ item }}
  sudo: True
  with_items:  
    - ipython 
    - python-matplotlib 
    - python-matplotlib-data 
    - python-pip 
    - python-pyfits 
    - python-numpy 
    - python-scipy 
    - python-virtualenv 
    - python-sphinx
    - python-pygments 
    - python-jinja2 
    - python-nose 
    - python-tornado 
    - cython 
    - python-zmq 
    - python-pywcs 
    - python-astropy 
    - python-numexpr 
    - python-tables 
    - python-pandas
    - ipython-notebook 
    - ipython-qtconsole
    - python-h5py

- name: Update pip to the last version
  script: update_pip.sh
  sudo: True
  
- name: install additional Python packages with pip
  pip: name={{ item }} extra_args="--upgrade"
  sudo: True
  with_items:  
    - pyopenssl 
    - ndg-httpsclient
    - pyasn1
    - astropy
    - aplpy
    - unittest-xml-reporting
    - psutil
    - progressbar
    - wcsaxes
    - fabric
    - jupyter
    - ipython
    - ipyparallel
    - montage-wrapper
    - pyFFTW
    - shapely
    - descartes
    
- name: install LOFAR dependencies repository
  apt_repository: repo='ppa:radio-astro/main'
  sudo: True

- name: install LOFAR dependencies
  apt: pkg={{ item }} update_cache=yes
  sudo: True
  with_items:
    - casacore2
    - libcasacore2-dev
    - python-casacore
    - casarest
    - casacore-data
    - montage
    - sagecal

