---
- name: Create a LOFAR-head instance
  hosts: localhost
  vars:
    count: 1
  tasks:
  - name: start the instance
    ec2:
      image: ami-57f2513c
      region: us-east-1
      instance_type: t2.micro
      key_name: jsmkey
      group: [ska]
      instance_tags: { Name: microhead, type: ska, env: production }
      wait: yes
      exact_count: "{{ count }}"
      count_tag: { type: ska }
    register: ec2
      
  - name: add the instance to the inventory
    add_host: name={{ item.public_ip }} groups=ska,production
    with_items: ec2.tagged_instances
    when: item.public_ip is defined
    
  - name: Add DNS entry
    route53:
      command: create
      zone: "lofarcloud.uk"
      record: "microhead.lofarcloud.uk"
      type: A
      ttl: 300
      value: "{{ item.public_ip }}"
    with_items: ec2.tagged_instances
    
  - name: wait for the ssh server
    wait_for: host={{ item.public_dns_name }} port=22 search_regex=OpenSSH
    with_items: ec2.tagged_instances
    when: item.public_dns_name is defined
    
