---
- name: Create an Ubuntu instance
  hosts: localhost
  vars:
    count: 1
  tasks:
  - name: start the instance
    ec2:
      image: ami-d05e75b8
      region: us-east-1
      instance_type: t2.micro
      key_name: jsmkey
      group: [ska]
      instance_tags: { Name: ansiblebook, type: ska, env: production }
      wait: yes
      exact_count: "{{ count }}"
      count_tag: { type: ska }
    register: ec2
      
  - name: wait for the instance
    add_host: host={{ item.public_dns_name }} groups=ska,production
    with_items: ec2.tagged_instances
    when: item.public_dns_name is defined
    
  - name: wait for the ssh server
    wait_for: host={{ item.public_dns_name }} port=22 search_regex=OpenSSH
    with_items: ec2.tagged_instances
    when: item.public_dns_name is defined

- name: configure LOFAR machine
  hosts: ska:&production
  sudo: True
  roles:
    - lofar